# Generated by Django 4.0.6 on 2022-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
