# Generated by Django 4.0.6 on 2022-07-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file4',
            new_name='file1',
        ),
    ]
